name: Run Unit Tests

on: [push]

defaults:
  run:
    working-directory: ./backend

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install Dependencies
        run: yarn

      - name: Run Unit Tests
        run: yarn test
