name: Run E2E Tests

on: [pull_request]
  
defaults:
  run:
    working-directory: ./backend

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-22.04
    
    services:
      postgresql:
        container_name: devlinks_postgres
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: devlinks

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OpenSSL
        run: sudo apt-get update -y && sudo apt-get install -y openssl

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      
      - name: Install Dependencies
        run: yarn
      
      - name: Run E2E Tests
        run: yarn test:e2e
        env:
          JWT_SECRET: test-jwt-secret-key
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/devlinks?schema=public"
